### ISSUE TITLE
attribute_mapper and date fields don't play well together

### ISSUE THREAD

**Issue by mguterl** [pahanix/delegates_attributes_to#2]
Currently, you cannot assign date or time attributes through delegates_attributes_to.

It raises MultiparameterAssignmentErrors in execute_callstrack_for_multiparameter_attributes because it unable to determine the klass on line 3044.

column_for_attribute needs to be smarter and look up the attribute on the delegate object.

This is with ActiveRecord 2.3.5.

**Comment by pahanix** [comment]
Thanks Michael for the case. I will take a look today. Do you mean assigning through date_select when sending a form?

**Comment by mguterl** [comment]
Yeah, it is when it is trying assemble the 1i, 2i, and 3i values into the actual Time object.

**Comment by mguterl** [comment]
I think this is all resolved
