### ISSUE TITLE
delegate item.attribute? method

### ISSUE THREAD

**Issue by kvdenden** [pahanix/delegates_attributes_to#4]
I was wondering why item.attribute? (in the example, this would be u.firstname?) is not delegated.
in the example, you can delegate u.contact.firstname to u.firstname, but u.contact.firstname? is not delegated.
After a quick look in the code, all that needs to be done to support this is adding '?' to the ATTRIBUTE_SUFFIXES array.

**Comment by pahanix** [comment]
Hey Ken!

Good catch! Thanks!
Pushed
